name: 'Setup environment for the build'

inputs:
    cache-disabled:
        description: 'gradle.cache-disabled'
        default: 'false'
    cache-read-only:
        description: 'gradle.cache-read-only'
        default: 'false'
    java-version:
        description: 'Java version'
        default: '21'

runs:
    using: 'composite'
    steps:
        -   name: Configure JDK
            uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 #v5.0.0
            with:
                distribution: 'zulu'
                java-version: ${{ inputs.java-version }}

        -   uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a #v4.4.3
            with:
                validate-wrappers: true
                cache-disabled: ${{ inputs.cache-disabled }}
                cache-read-only: ${{ inputs.cache-read-only }}

        -   name: Cache Gradle Wrapper
            uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
            id: gradle-wrapper-cache
            with:
                path: ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-wrapper-
                enableCrossOsArchive: true

        -   name: Cache Node Modules
            uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
            id: gradle-yarn-cache
            with:
                path: build/js/node_modules
                key: ${{ runner.os }}-yarn-${{ hashFiles('gradle/js/yarn.lock') }}
                restore-keys: ${{ runner.os }}-yarn-
                enableCrossOsArchive: true

        -   name: Initialize Gradle wrapper
            if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
            run: chmod +x ./gradlew
            shell: "bash"

        -   name: Cache Konan
            uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 #v4.2.4
            with:
                path: |
                    ~/.konan/cache
                    ~/.konan/dependencies
                    ~/.konan/kotlin-native-macos*
                    ~/.konan/kotlin-native-mingw*
                    ~/.konan/kotlin-native-windows*
                    ~/.konan/kotlin-native-linux*
                    ~/.konan/kotlin-native-prebuilt-macos*
                    ~/.konan/kotlin-native-prebuilt-mingw*
                    ~/.konan/kotlin-native-prebuilt-windows*
                    ~/.konan/kotlin-native-prebuilt-linux*
                key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-konan-

        -   if: matrix.os == 'Windows'
            uses: msys2/setup-msys2@fb197b72ce45fb24f17bf3f807a388985654d1f2 #v2.27.0
            with:
                release: false
                install: mingw-w64-x86_64-openssl
