name: CI Main

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
            - ".editorconfig"
            - ".gitattributes"
            - ".gitignore"
            - "oas/**"

permissions:
    contents: read

concurrency:
    group: ci-main-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            -   name: Validate commit messages
                uses: ./.github/actions/commit-messages-validation

    build:
        needs:
            - validate
        uses: ./.github/workflows/run-build.yml
