name: CI Publish

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to publish'
                required: true

permissions:
    contents: read

concurrency:
    group: ci-publish-${{ github.workflow }}-${{ github.event.ref }}
    cancel-in-progress: true

jobs:
    publish:
        uses: ./.github/workflows/run-publish.yml
        secrets: inherit
        with:
            version: ${{ github.event.inputs.version }}
